/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Paneles.Admin_LOGGER;
import Paneles.Perfil_Bancario;
import Paneles.Simulador_Credito;
import Paneles.Transacciones;
import javax.swing.JOptionPane;

/**
 *
 * @author jonathan.mata
 */
public class Bancogeneral extends javax.swing.JFrame {

    boolean acceso = false;

    /**
     * Creates new form Bancogeneral
     */
    public Bancogeneral() {
        initComponents();
        transparencia();
        this.setLocationRelativeTo(null);
    }

    public void perfil(){
        Perfil_Bancario perf = new Perfil_Bancario();
        frame.add(perf);
        perf.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        frame = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Perfil2 = new javax.swing.JButton();
        Perfil = new javax.swing.JButton();
        Perfil1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Group 50.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 0, 1190, 740));

        frame.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout frameLayout = new javax.swing.GroupLayout(frame);
        frame.setLayout(frameLayout);
        frameLayout.setHorizontalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameLayout.setVerticalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 940, 740));

        Perfil2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Component 4.png"))); // NOI18N
        Perfil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Perfil2ActionPerformed(evt);
            }
        });
        jPanel1.add(Perfil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 190, 80));

        Perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Group 40.png"))); // NOI18N
        Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilActionPerformed(evt);
            }
        });
        jPanel1.add(Perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 80));

        Perfil1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Group 54.png"))); // NOI18N
        Perfil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Perfil1ActionPerformed(evt);
            }
        });
        jPanel1.add(Perfil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 210, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/FLOWI_landing_10 abr-05.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 380, 580, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Group 50.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilActionPerformed
        // TODO add your handling code here:
        Admin_LOGGER adm = new Admin_LOGGER();
        frame.add(adm);
        adm.setVisible(true);
    }//GEN-LAST:event_PerfilActionPerformed

    private void Perfil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Perfil1ActionPerformed
        // TODO add your handling code here:
        Simulador_Credito sim = new Simulador_Credito();
        frame.add(sim);
        sim.setVisible(true);
    }//GEN-LAST:event_Perfil1ActionPerformed

    private void Perfil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Perfil2ActionPerformed
        // TODO add your handling code here:
        Transacciones tra = new Transacciones();
        frame.add(tra);
        tra.setVisible(true);
    }//GEN-LAST:event_Perfil2ActionPerformed

    public void transparencia() {
        Perfil.setOpaque(false);
        Perfil.setContentAreaFilled(false);
        Perfil.setBorderPainted(false);
        Perfil1.setOpaque(false);
        Perfil1.setContentAreaFilled(false);
        Perfil1.setBorderPainted(false);
        Perfil2.setOpaque(false);
        Perfil2.setContentAreaFilled(false);
        Perfil2.setBorderPainted(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bancogeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bancogeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bancogeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bancogeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bancogeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Perfil;
    private javax.swing.JButton Perfil1;
    private javax.swing.JButton Perfil2;
    public static javax.swing.JDesktopPane frame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
