/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Data;
import Clases.Sentences;
import javax.swing.JOptionPane;

/**
 *
 * @author jonathan.mata
 */
public class Register extends javax.swing.JFrame {

    Sentences datos = new Sentences();
    Data data = new Data();

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        transparencia();
        this.setLocationRelativeTo(null);
    }

    public void transparencia() {
        btn_registrar_reg.setOpaque(false);
        btn_registrar_reg.setContentAreaFilled(false);
        btn_registrar_reg.setBorderPainted(false);
    }

    public void limpiar() {
        txt_usr_reg.setText("");
        txt_psswd_reg.setText("");
        txt_psswd_reg2.setText("");
    }

    public void limpiarre() {
        txt_psswd_reg.setText("");
        txt_psswd_reg2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_usr_reg = new javax.swing.JTextField();
        txt_psswd_reg = new javax.swing.JPasswordField();
        txt_psswd_reg2 = new javax.swing.JPasswordField();
        btn_registrar_reg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_usr_reg.setBorder(null);
        txt_usr_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usr_regActionPerformed(evt);
            }
        });
        jPanel1.add(txt_usr_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 174, 370, 30));

        txt_psswd_reg.setBorder(null);
        jPanel1.add(txt_psswd_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 360, 30));

        txt_psswd_reg2.setBorder(null);
        jPanel1.add(txt_psswd_reg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 360, 30));

        btn_registrar_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrar_regActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrar_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Desktop - 2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrar_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrar_regActionPerformed
        // TODO add your handling code here:
        if (txt_usr_reg.getText().isEmpty() || txt_psswd_reg.getText().isEmpty() || txt_psswd_reg2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "DEBE INGRESAR DATOS");
            this.setVisible(false);
            Login log = new Login();
            log.setVisible(true);
        } else {
            if (txt_psswd_reg.getText().equals(txt_psswd_reg2.getText())) {
                data.setUser(txt_usr_reg.getText());
                data.setPsswd(txt_psswd_reg.getText());
                datos.registro(data);
                JOptionPane.showMessageDialog(null, "DATOS REGISTRADOS");
                limpiar();
                this.setVisible(false);
                Login log = new Login();
                log.setVisible(true);

            } else if (txt_psswd_reg.getText() != (txt_psswd_reg2.getText())) {
                JOptionPane.showMessageDialog(null, "RE PASSWORD INCORRECT");
                limpiarre();
            }
        }
    }//GEN-LAST:event_btn_registrar_regActionPerformed

    private void txt_usr_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usr_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usr_regActionPerformed

    /**
     * @param args the command line aarguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrar_reg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_psswd_reg;
    private javax.swing.JPasswordField txt_psswd_reg2;
    private javax.swing.JTextField txt_usr_reg;
    // End of variables declaration//GEN-END:variables
}
